import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Contact from '../src/Contact'
import Hero from '../src/Hero'
import Navbar from '../src/Navbar'
import styles from '../styles/Home.module.css'
import { FaWhatsapp } from 'react-icons/fa';
import Services from '../src/Services'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Hero />
        <Services />
        <Contact />

      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
