import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Contact from '../src/Contact'
import Services from '../src/Services'
import Hero from '../src/Hero'
import Navbar from '../src/Navbar'
import Footer from '../src/Footer'
import api from '../src/api'
import { HeroInfo, ServiceInfo } from '../src/types'

interface Props {
  heroInfo: HeroInfo;
  services: ServiceInfo[];
  }

const Home: NextPage<Props> = ({ heroInfo, services }) => {
  console.log(heroInfo)
  console.log(services)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto">
        <Navbar />
        <Hero title={heroInfo.title} image_url={heroInfo.image} />
        <Services />
        <Contact />
        <Footer />
      </main>
      <footer>
      </footer>
    </div>
  )
}
export const getStaticProps: GetStaticProps = async () => {
  const heroInfo = await api.list()
/*   const services = await api.services() */

  return {
    props: {
      heroInfo,
/*       services, */
    },
  };
};

export default Home
